# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "rpmsrv" do |rpmsrv|
    rpmsrv.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    rpmsrv.vm.hostname = "rpmsrv"
    rpmsrv.vm.provision "shell", path: "rpm.sh"
  end

end

